---

- name: Playbook to create partition for Ceph
  host: storage
  remote_user: root
  become: yes
  tasks:
    - name: Create Partition
      apt:
         name: xfsprogs
         state: present
         update_cache: yes
    - name: Copy script
      copy: src=../scripts/ceph-bootstrap.sh dest=/root/ mode=0777
    - name: Copy disks.lst
      copy: src=../scripts/disks.lst dest=/root/ mode=0777
    - name: Execute the script
      shell: /bin/bash /root/ceph-bootstrap.sh >> /root/ceph.out
      ignore_errors: yes
      become_user: root
